/**
 * Agent Memory — persistent lessons learned and session changelog.
 *
 * ## Design
 *
 * - **lessons.md** — accumulates patterns, fixes, and gotchas across sessions.
 *   Loaded at session start as `<system-reminder>`. Updated after user corrections.
 *
 * - **CHANGELOG.md** — portable long-term memory tracking session summaries,
 *   failed approaches (TRIED/FAILED), and working solutions (WORKS).
 *   Prevents the agent from re-attempting dead ends.
 *
 * Both files live in the virtual project but are managed automatically — the
 * agent reads them but the system handles persistence.
 */

// ─── Types ──────────────────────────────────────────────────────────────────

export interface LessonEntry {
  date: string
  type: 'FIX' | 'PATTERN' | 'GOTCHA' | 'TRIED' | 'WORKS'
  content: string
}

export interface ChangelogEntry {
  date: string
  sessionId: string
  prompt: string
  filesCreated: string[]
  filesEdited: string[]
  approaches: { tried: string; result: 'works' | 'failed'; note: string }[]
  lessons: string[]
}

// ─── Lesson Management ─────────────────────────────────────────────────────

const LESSONS_HEADER = `# Bloom Agent — Lessons Learned

> Auto-generated by the agent. Do not edit manually.
> Format: \`## YYYY-MM-DD\` → \`- TYPE: content\`
> Types: FIX (correction), PATTERN (user preference), GOTCHA (non-obvious behavior), TRIED (failed approach), WORKS (proven solution)

`

export function formatLessons(entries: LessonEntry[]): string {
  if (entries.length === 0) return LESSONS_HEADER

  // Group by date
  const byDate = new Map<string, LessonEntry[]>()
  for (const entry of entries) {
    const existing = byDate.get(entry.date) || []
    existing.push(entry)
    byDate.set(entry.date, existing)
  }

  let output = LESSONS_HEADER
  for (const [date, dayEntries] of [...byDate.entries()].sort().reverse()) {
    output += `## ${date}\n`
    for (const e of dayEntries) {
      output += `- ${e.type}: ${e.content}\n`
    }
    output += '\n'
  }

  return output.trim() + '\n'
}

export function parseLessons(raw: string): LessonEntry[] {
  const entries: LessonEntry[] = []
  let currentDate = ''

  for (const line of raw.split('\n')) {
    const dateMatch = line.match(/^## (\d{4}-\d{2}-\d{2})/)
    if (dateMatch) {
      currentDate = dateMatch[1]
      continue
    }

    const entryMatch = line.match(/^- (FIX|PATTERN|GOTCHA|TRIED|WORKS): (.+)$/)
    if (entryMatch && currentDate) {
      entries.push({
        date: currentDate,
        type: entryMatch[1] as LessonEntry['type'],
        content: entryMatch[2].trim(),
      })
    }
  }

  return entries
}

/**
 * Add a new lesson entry with today's date.
 */
export function addLesson(
  entries: LessonEntry[],
  type: LessonEntry['type'],
  content: string,
): LessonEntry[] {
  const today = new Date().toISOString().slice(0, 10)
  return [...entries, { date: today, type, content }]
}

/**
 * Format lessons as a compact `<system-reminder>` for injection into the agent context.
 */
export function lessonsToSystemReminder(entries: LessonEntry[]): string {
  if (entries.length === 0) return ''

  // Only include the most recent 20 entries to keep context lean
  const recent = entries.slice(-20)
  const today = new Date().toISOString().slice(0, 10)
  const todayEntries = recent.filter((e) => e.date === today)
  const olderEntries = recent.filter((e) => e.date !== today)

  let output = '<system-reminder>\n'
  output += '## Agent Lessons Learned\n\n'

  if (todayEntries.length > 0) {
    output += "**Today's learnings:**\n"
    for (const e of todayEntries) {
      output += `- ${e.type}: ${e.content}\n`
    }
    output += '\n'
  }

  if (olderEntries.length > 0) {
    output += '**Previous sessions:**\n'
    for (const e of olderEntries.slice(-10)) {
      output += `- ${e.type}: ${e.content}\n`
    }
  }

  output += '\nApply these lessons. Do not repeat TRIED/FAILED approaches.\n'
  output += '</system-reminder>'
  return output
}

// ─── CHANGELOG Management ───────────────────────────────────────────────────

const CHANGELOG_HEADER = `# Bloom Agent — CHANGELOG

> Auto-generated session log. Tracks what was built, what failed, and what worked.
> The agent reads this before new sessions to avoid repeating dead ends.

`

export function formatChangelog(entries: ChangelogEntry[]): string {
  if (entries.length === 0) return CHANGELOG_HEADER

  let output = CHANGELOG_HEADER
  for (const entry of [...entries].reverse()) {
    output += `## ${entry.date} — ${entry.sessionId}\n\n`
    output += `**Prompt:** ${entry.prompt}\n\n`

    if (entry.filesCreated.length > 0) {
      output += `**Created:** ${entry.filesCreated.join(', ')}\n\n`
    }
    if (entry.filesEdited.length > 0) {
      output += `**Edited:** ${entry.filesEdited.join(', ')}\n\n`
    }

    if (entry.approaches.length > 0) {
      output += `**Approaches:**\n`
      for (const a of entry.approaches) {
        const icon = a.result === 'works' ? '✅' : '❌'
        output += `- ${icon} ${a.tried}: ${a.note}\n`
      }
      output += '\n'
    }

    if (entry.lessons.length > 0) {
      output += `**Lessons:**\n`
      for (const l of entry.lessons) {
        output += `- ${l}\n`
      }
      output += '\n'
    }

    output += '---\n\n'
  }

  return output.trim() + '\n'
}

export function parseChangelog(raw: string): ChangelogEntry[] {
  const entries: ChangelogEntry[] = []
  const sections = raw.split(/^## /m).slice(1) // Skip header

  for (const section of sections) {
    const lines = section.trim().split('\n')
    const headerLine = lines[0] || ''
    const [datePart, sessionPart] = headerLine.split(' — ')
    const date = (datePart || '').trim()
    const sessionId = (sessionPart || '').trim()

    if (!date) continue

    const entry: ChangelogEntry = {
      date,
      sessionId,
      prompt: '',
      filesCreated: [],
      filesEdited: [],
      approaches: [],
      lessons: [],
    }

    let currentSection = ''
    for (let i = 1; i < lines.length; i++) {
      const line = lines[i]

      if (line.startsWith('**Prompt:**')) {
        entry.prompt = line.replace('**Prompt:**', '').trim()
      } else if (line.startsWith('**Created:**')) {
        entry.filesCreated = line
          .replace('**Created:**', '')
          .trim()
          .split(',')
          .map((s) => s.trim())
          .filter(Boolean)
      } else if (line.startsWith('**Edited:**')) {
        entry.filesEdited = line
          .replace('**Edited:**', '')
          .trim()
          .split(',')
          .map((s) => s.trim())
          .filter(Boolean)
      } else if (line.startsWith('**Approaches:**')) {
        currentSection = 'approaches'
      } else if (line.startsWith('**Lessons:**')) {
        currentSection = 'lessons'
      } else if (line.startsWith('---')) {
        currentSection = ''
      } else if (currentSection === 'approaches' && line.match(/^- [✅❌]/)) {
        const match = line.match(/^- ([✅❌]) (.+?): (.+)$/)
        if (match) {
          entry.approaches.push({
            tried: match[2].trim(),
            result: match[1] === '✅' ? 'works' : 'failed',
            note: match[3].trim(),
          })
        }
      } else if (currentSection === 'lessons' && line.startsWith('- ')) {
        entry.lessons.push(line.replace('- ', '').trim())
      }
    }

    entries.push(entry)
  }

  return entries
}

/**
 * Create a changelog entry from a completed agent session.
 */
export function createChangelogEntry(params: {
  sessionId: string
  prompt: string
  filesCreated: string[]
  filesEdited: string[]
  approaches: ChangelogEntry['approaches']
  lessons: string[]
}): ChangelogEntry {
  return {
    date: new Date().toISOString().slice(0, 10),
    sessionId: params.sessionId,
    prompt: params.prompt,
    filesCreated: params.filesCreated,
    filesEdited: params.filesEdited,
    approaches: params.approaches,
    lessons: params.lessons,
  }
}

/**
 * Format recent changelog entries as a compact `<system-reminder>`.
 * Only includes "TRIED/FAILED" approaches to prevent re-attempting dead ends.
 */
export function changelogToSystemReminder(entries: ChangelogEntry[]): string {
  // Extract only failed approaches for context efficiency
  const failedApproaches: string[] = []
  for (const entry of entries.slice(-5)) {
    for (const a of entry.approaches) {
      if (a.result === 'failed') {
        failedApproaches.push(`- ❌ ${a.tried}: ${a.note}`)
      }
    }
  }

  if (failedApproaches.length === 0) return ''

  return `<system-reminder>
## Previously Failed Approaches (DO NOT RETRY)

${failedApproaches.join('\n')}

These approaches were tried and failed. Find a different solution.
</system-reminder>`
}

// ─── Session ID Generator ───────────────────────────────────────────────────

export function generateSessionId(): string {
  const now = new Date()
  const date = now.toISOString().slice(0, 10).replace(/-/g, '')
  const time = now.toTimeString().slice(0, 5).replace(':', '')
  const rand = Math.random().toString(36).slice(2, 6)
  return `${date}-${time}-${rand}`
}
