import LegalPage from './LegalPage'
import { usePageTitle } from '../lib/usePageTitle'

export default function TermsPage() {
  usePageTitle('Terms of Service')
  return (
    <LegalPage title="Terms of Service" lastUpdated="June 6, 2026">
      <h2>1. About OpenThorn</h2>
      <p>
        OpenThorn is a free AI web builder. You describe what you want; OpenThorn generates
        production-grade code using the AI provider of your choice. The service is provided
        at no charge and without a subscription.
      </p>

      <h2>2. Acceptance of Terms</h2>
      <p>
        By creating an account or using the service, you agree to these Terms of Service.
        If you do not agree, do not use OpenThorn.
      </p>

      <h2>3. Accounts</h2>
      <ul>
        <li>You must provide a valid email address to register.</li>
        <li>
          You are responsible for maintaining the confidentiality of your account
          credentials.
        </li>
        <li>
          You must notify us immediately at <strong><a href="mailto:mys.thomas00@gmail.com">mys.thomas00@gmail.com</a></strong> if you suspect
          unauthorised access to your account.
        </li>
        <li>You must be at least 16 years old to use the service.</li>
      </ul>

      <h2>4. Bring Your Own Keys (BYOK)</h2>
      <p>
        OpenThorn does not provide AI model access. You connect your own API keys from
        providers such as OpenAI, Anthropic, or Google. By doing so:
      </p>
      <ul>
        <li>
          Your API keys are used to make requests directly to the AI provider. OpenThorn
          does not store, log, or charge for your API usage.
        </li>
        <li>
          You are solely responsible for the security of your API keys. If a key is
          compromised, revoke it immediately with your provider.
        </li>
        <li>
          You are responsible for all costs incurred with your AI provider. OpenThorn
          charges you nothing.
        </li>
        <li>
          You must comply with the terms of service of the AI provider whose keys you use.
        </li>
      </ul>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to use OpenThorn to:</p>
      <ul>
        <li>Violate any applicable law or regulation.</li>
        <li>
          Generate content that is illegal, harmful, defamatory, or infringes third-party
          rights.
        </li>
        <li>
          Attempt to gain unauthorised access to the service or its infrastructure.
        </li>
        <li>Interfere with or disrupt the service or other users.</li>
        <li>Use automated means to access the service beyond normal usage patterns.</li>
      </ul>

      <h2>6. User Content</h2>
      <p>
        You retain ownership of the prompts you write and the code generated in response to
        your prompts. By using the service, you grant OpenThorn a limited, non-exclusive
        licence to store and serve your content solely to provide the service to you.
      </p>
      <p>
        You are responsible for ensuring that any content you submit does not infringe
        third-party intellectual property rights.
      </p>

      <h2>7. Community Features</h2>
      <p>
        If you share a project publicly through the Community feature, it becomes visible to
        other users. You retain ownership of that content, but you grant other users the
        right to view and fork it within the service.
      </p>
      <p>
        We reserve the right to remove publicly shared content that violates these Terms or
        applicable law.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        The OpenThorn name, logo, and interface design are our intellectual property.
        Nothing in these Terms transfers any ownership of OpenThorn's brand or software to
        you. Code output generated by the service belongs to you.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        The service is provided <strong>"as is"</strong> and{' '}
        <strong>"as available"</strong> without warranties of any kind, either express or
        implied. We do not warrant that the service will be uninterrupted, error-free, or
        that generated code will be fit for any particular purpose. You use the service at
        your own risk.
      </p>

      <h2>10. EU Artificial Intelligence Act</h2>
      <p>
        OpenThorn is an AI-powered service subject to Regulation (EU) 2024/1689 (the EU AI
        Act). The following disclosures apply:
      </p>
      <ul>
        <li>
          <strong>You are interacting with AI.</strong> The service uses large language
          models to generate code and website content. All output is AI-generated.
        </li>
        <li>
          <strong>Bring Your Own Keys.</strong> OpenThorn does not operate AI models.
          You connect your own API keys from third-party AI providers (e.g. OpenAI,
          Anthropic, Google). Those providers are responsible for their models' compliance
          with applicable AI regulations.
        </li>
        <li>
          <strong>Minimal-risk use case.</strong> OpenThorn is used exclusively for code
          and website generation. It is not used for any high-risk purpose as defined in
          Annex III of the EU AI Act (including but not limited to biometric
          identification, employment decisions, credit scoring, or law enforcement).
        </li>
        <li>
          <strong>Human review recommended.</strong> AI-generated code may contain errors,
          security vulnerabilities, or inaccuracies. You are responsible for reviewing,
          testing, and validating all output before deploying it in any production
          environment.
        </li>
        <li>
          <strong>No prohibited practices.</strong> OpenThorn does not use AI to
          manipulate users subliminally, exploit vulnerabilities, perform social scoring,
          or engage in any practice prohibited under Art. 5 of the EU AI Act.
        </li>
      </ul>

      <h2>11. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by applicable law, OpenThorn and its operators
        shall not be liable for any indirect, incidental, special, consequential, or
        punitive damages arising out of or related to your use of the service. Because the
        service is provided free of charge, our aggregate liability to you for direct
        damages shall not exceed the greater of the fees you paid us in the twelve months
        preceding the claim or €0.
      </p>
      <p>
        Nothing in these Terms limits or excludes liability for fraud, gross negligence,
        or death or personal injury caused by our negligence, or any other liability that
        cannot be limited or excluded under applicable mandatory law. If you are a
        consumer, your statutory rights under applicable consumer protection law
        (including the Italian Consumer Code, D.Lgs. 206/2005) are not affected by
        these Terms.
      </p>

      <h2>12. Termination</h2>
      <p>
        We may suspend or terminate your account if you breach these Terms. You may delete
        your account at any time by contacting us at <strong><a href="mailto:mys.thomas00@gmail.com">mys.thomas00@gmail.com</a></strong>.
        Termination does not affect any accrued rights or obligations.
      </p>

      <h2>13. Changes to Terms</h2>
      <p>
        We may update these Terms at any time by posting the revised version on this page
        with an updated date. Continued use of the service after the update constitutes
        acceptance. If you do not accept the changes, stop using the service and delete your
        account.
      </p>

      <h2>14. Governing Law</h2>
      <p>
        These Terms are governed by Italian law. For users who are consumers under the
        Italian Consumer Code (D.Lgs. 206/2005), the mandatory consumer protection
        provisions of your country of residence also apply. Disputes shall be subject to
        the exclusive jurisdiction of the courts of <strong>Rome</strong>, Italy,
        except where mandatory consumer law provides otherwise.
      </p>

      <h2>15. Contact</h2>
      <p>
        For any questions about these Terms, contact us at <strong><a href="mailto:mys.thomas00@gmail.com">mys.thomas00@gmail.com</a></strong>.
      </p>
    </LegalPage>
  )
}
